#Python Fundamentals 3

3 types of data:
    cross-sectional data: gather by entity, unit of observation
    time series data: tracking 1 thing over a period of time
    longitudinal/panel data: multiple entities and multiple time periods

In [1]:
l = []
for i in range(35):
    if i%2 == 0:
        l.append(i)
l

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]

In [4]:
l = [i for i in range(35) if i%2 == 0]
l

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]

In [3]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
fruit = ['apple','orange','mango','pear']
[i.capitalize() for i in fruit]

['Apple', 'Orange', 'Mango', 'Pear']

In [10]:
def func_a(l):
    l2 = [i.upper() for i in l]
    return l2
func_a(fruit)

['APPLE', 'ORANGE', 'MANGO', 'PEAR']

In [14]:
func_a(['knicks','rummy'])

['KNICKS', 'RUMMY']

In [36]:
def clock_angle(h,m):
    #hour moves forward by 1/60th per minute
    z = 60 * h + m
    angle = .5 * z - 6 * m
    if angle<0:
        angle = angle*-1
    elif angle>180:
        angle = 360 - angle
    return angle

In [39]:
clock_angle(12,15)

82.5

In [5]:
import numpy as np

In [6]:
np.log(10)

2.302585092994046

In [7]:
ar = np.array([3,6,1,9,12])
ar

array([ 3,  6,  1,  9, 12])

In [8]:
ar+10

array([13, 16, 11, 19, 22])

In [9]:
ar/3

array([1.        , 2.        , 0.33333333, 3.        , 4.        ])

In [11]:
ar2 = np.array([[-1,2,5],[3,7,12]])
ar2

array([[-1,  2,  5],
       [ 3,  7, 12]])

In [12]:
ar2.T.shape

(3, 2)

In [13]:
import pandas as pd